'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17626
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Twinvision.Glue.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vul eerst de configuratie gegevens.
        '''</summary>
        Friend ReadOnly Property messageConfigurationMissing() As String
            Get
                Return ResourceManager.GetString("messageConfigurationMissing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Verbinding met Multivers Extended is gemaakt.
        '''</summary>
        Friend ReadOnly Property messageConnected() As String
            Get
                Return ResourceManager.GetString("messageConnected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Verbinding maken met Multivers Extended....
        '''</summary>
        Friend ReadOnly Property messageConnecting() As String
            Get
                Return ResourceManager.GetString("messageConnecting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gegevens zijn opgehaald.
        '''</summary>
        Friend ReadOnly Property messageDataSelected() As String
            Get
                Return ResourceManager.GetString("messageDataSelected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Het is niet gelukt het label te ontwerpen:.
        '''</summary>
        Friend ReadOnly Property messageLabelDesignError() As String
            Get
                Return ResourceManager.GetString("messageLabelDesignError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Het is niet gelukt om de labels af te drukken:.
        '''</summary>
        Friend ReadOnly Property messageLabelPrintError() As String
            Get
                Return ResourceManager.GetString("messageLabelPrintError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stel eerst de labelprinter in bij de configuratie gegevens..
        '''</summary>
        Friend ReadOnly Property messageNoLabelPrinter() As String
            Get
                Return ResourceManager.GetString("messageNoLabelPrinter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Selecteer eerst minimaal 1 pakbon regel..
        '''</summary>
        Friend ReadOnly Property messageNoSelection() As String
            Get
                Return ResourceManager.GetString("messageNoSelection", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gegevens ophalen....
        '''</summary>
        Friend ReadOnly Property messageSelectData() As String
            Get
                Return ResourceManager.GetString("messageSelectData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Er kan geen verbinding worden gemaakt met Multivers Extended.
        '''</summary>
        Friend ReadOnly Property messageUnableToConnect() As String
            Get
                Return ResourceManager.GetString("messageUnableToConnect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Het is niet gelukt de gegevens op te halen:.
        '''</summary>
        Friend ReadOnly Property messageUnableToSelectData() As String
            Get
                Return ResourceManager.GetString("messageUnableToSelectData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT lb183.nrpakbon Pakbonnummer, lb183.&quot;datum-pak&quot; Datum, lb183.cddeb Debiteurnummer, ba001.naamorg Debiteurnaam
        '''FROM pub.&quot;lb-185&quot; lb185, pub.&quot;lb-455&quot; lb455, pub.&quot;lb-183&quot; lb183, pub.&quot;aa-270&quot; aa270, pub.&quot;ba-001&quot; ba001
        '''WHERE lb185.cdadmin = lb455.cdadmin AND lb185.cdadmin = lb183.cdadmin AND lb185.cdadmin = aa270.cdadmin AND lb185.cdpartij = lb455.cdpartij AND lb185.cdprodukt = lb455.cdprodukt AND lb185.cdstandeenhd = lb455.cdstandeenhd
        '''AND lb185.nrmutatie = lb183.nrpakbon AND lb183.cddeb = aa270.cddeb  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property SQLSelectPackList() As String
            Get
                Return ResourceManager.GetString("SQLSelectPackList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT lb183.nrpakbon Pakbonnummer, lb185.cdprodukt Productnummer, &apos;&apos; Productnaam, &apos;&apos; Productnummerdebiteur, lb185.cdpartij Partijnummer, LEFT(lb455.&quot;omschr-60&quot;, 19) Partijomschrijving, lb185.cdstandeenhd Eenheid, ba001.cdtaal Taalcode, lb183.cddeb Debiteurnummer
        '''FROM pub.&quot;lb-185&quot; lb185, pub.&quot;lb-455&quot; lb455, pub.&quot;lb-183&quot; lb183, pub.&quot;aa-270&quot; aa270, pub.&quot;ba-001&quot; ba001
        '''WHERE lb185.cdadmin = lb455.cdadmin AND lb185.cdadmin = lb183.cdadmin  AND lb185.cdpartij = lb455.cdpartij AND lb185.cdprodukt = lb455.cdprodu [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property SQLSelectPackListLine() As String
            Get
                Return ResourceManager.GetString("SQLSelectPackListLine", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT af801.&quot;id-tekst&quot; Productnummer, af801.tekst Productnaam, af801.cdsoort Taalcode
        '''FROM pub.&quot;af-801&quot; af801
        '''WHERE af801.cdtabel=&apos;bb-062&apos;.
        '''</summary>
        Friend ReadOnly Property SQLSelectProductDescription() As String
            Get
                Return ResourceManager.GetString("SQLSelectProductDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT bb196.cddebprod Productnummerdebiteur, bb196.cdprodukt Productnummer, bb196.cdstandeenhd Eenheid, aa270.cddeb Debiteurnummer
        '''FROM pub.&quot;af-316&quot; af316 INNER JOIN pub.&quot;bb-196&quot; bb196 ON af316.cdgrp = bb196.cdgrp INNER JOIN pub.&quot;aa-270&quot; aa270 ON af316.&quot;id-groep&quot; = aa270.cddeb.
        '''</summary>
        Friend ReadOnly Property SQLSelectProductNumberCustomer() As String
            Get
                Return ResourceManager.GetString("SQLSelectProductNumberCustomer", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
